export enum SoapQueryOperatorEnumeration {
    EQUALTO,
    NOTEQUALTO,
    GREATERTHAN,
    GREATERTHANOREQUAL,
    LESSTHAN,
    LESSTHANOREQUAL,
    RANGEOFDATA,
    IN,
    STARTSWITH,
    ENDSWITH,
    LIKE
}